server:
  port: 8080
spring:
  application:
    name: API-Gateway
    
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: Microservices-Communication
              uri: lb://MICROSERVICES-COMMUNICATION
              predicates:
                - Path=/microservices/**
              filters:
                - StripPrefix=1

            - id: Calling-Service
              uri: lb://CALLING-SERVICE
              predicates:
                - Path=/calling/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
